name: prompt
version: 0.1.7
author: Sean Eagan <seaneagan1@gmail.com>
description: Command-line prompting that is easy to data-drive, customize, and test.
homepage: https://github.com/seaneagan/prompt
dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  mock: '>=0.11.0 <0.12.0'
  supports_color: '>=0.1.1 <0.2.0'
  when: '>=0.2.0 <0.3.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
